// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCVmO7Z5laT9kKY69q6FISQ7J-XhOszY',
    appId: '1:484090581015:web:620e5c5abe28be19ac0c52',
    messagingSenderId: '484090581015',
    projectId: 'projectkalihcafe',
    authDomain: 'projectkalihcafe.firebaseapp.com',
    storageBucket: 'projectkalihcafe.appspot.com',
    measurementId: 'G-3H5LLM0841',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC4kPr9KemvY9LcsrQdPPZEOW_quPz8kw',
    appId: '1:484090581015:android:6e9c91e5ed6bd0a5ac0c52',
    messagingSenderId: '484090581015',
    projectId: 'projectkalihcafe',
    storageBucket: 'projectkalihcafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi35n7Wjba5vA1sFtnlSFIPrHHnvdkvBU',
    appId: '1:484090581015:ios:351e2dcbbc1bf15aac0c52',
    messagingSenderId: '484090581015',
    projectId: 'projectkalihcafe',
    storageBucket: 'projectkalihcafe.appspot.com',
    iosBundleId: 'com.example.khalih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi35n7Wjba5vA1sFtnlSFIPrHHnvdkvBU',
    appId: '1:484090581015:ios:351e2dcbbc1bf15aac0c52',
    messagingSenderId: '484090581015',
    projectId: 'projectkalihcafe',
    storageBucket: 'projectkalihcafe.appspot.com',
    iosBundleId: 'com.example.khalih',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYCVmO7Z5laT9kKY69q6FISQ7J-XhOszY',
    appId: '1:484090581015:web:0abf08b8f8b2f99eac0c52',
    messagingSenderId: '484090581015',
    projectId: 'projectkalihcafe',
    authDomain: 'projectkalihcafe.firebaseapp.com',
    storageBucket: 'projectkalihcafe.appspot.com',
    measurementId: 'G-W4R9JXEYBC',
  );

}